[workspace]
authors = ["asquebay <baymaxbay23@gmail.com>"]
channels = ["conda-forge"]
description = "Console utility for managing tasks in Git projects"
name = "Git-task-manager"
platforms = ["linux-64", "win-64", "osx-64", "osx-arm64"]
version = "0.1.0-beta"

[tasks]
# Сборка исполняемого файла PyInstaller в корень проекта
build = "pyinstaller --clean --onefile --log-level=INFO --name 'git-task' --paths . --distpath . src/main.py"

# Запуск в режиме разработки
dev = "python src/main.py"

[dependencies]
python = ">3.10,<3.12"
rich = ">=13.0.0"
pyinstaller = ">=6.0.0"
prompt-toolkit = ">=3.0.53,<4"
